apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nestjs-api-template.fullname" . }}
  labels:
    {{- include "nestjs-api-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nestjs-api-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nestjs-api-template.selectorLabels" . | nindent 8 }}
      {{- if .Values.prometheus.scrape }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nestjs-api-template.fullname" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "nestjs-api-template.fullname" . }}-config
          env:
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nestjs-api-template.fullname" . }}-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nestjs-api-template.fullname" . }}-secrets
                  key: JWT_REFRESH_SECRET
            - name: APP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "nestjs-api-template.fullname" . }}-secrets
                  key: APP_ENCRYPTION_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | default (printf "%s-secrets" (include "nestjs-api-template.fullname" .)) }}
                  key: {{ .Values.database.passwordKey | default "DB_PASSWORD" }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
