apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nestjs-api-template.fullname" . }}-secrets
  labels:
    {{- include "nestjs-api-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  APP_ENCRYPTION_KEY: {{ .Values.secrets.appEncryptionKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "postgres" | quote }}
